#!/bin/bash

#assign variables
ACTION=${1}

function create_file(){
	touch "${1}-54321"
}

function display_help(){

cat << EOF
Usage: ${0} {-h|--help |-c|--create} <filename>

OPTIONS:
	-c|--create Create a new file
	-h|--help Display the command help

Examples:
	Display help:
		$ ${0} -h
	Create a new file:
		$ ${0}-c foo.txt

EOF
}

case "$ACTION" in
	-h|--help)
		display_help
		;;
	-c|--create)
		create_file "${2:-server}"
		;;
	*)
	echo "Usage ${0} {-h|-c}"
	exit 1
esac
